dist: trusty
language: php

php: 7.3

cache:
  bundler: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
    - "$HOME/.npm"

addons:
  chrome: stable

before_install:
  - phpenv config-rm xdebug.ini
  - phpenv config-add .travis-ci/travis.php.ini
  - phpenv rehash

  - composer self-update
  - composer --version
  - google-chrome-stable --version

install:
  # Add Composer's local bin directory to the PATH so that we will be running
  # our installed versions of Drush, PHPCS, Behat, etc.
  - export PATH="$HOME/.composer/vendor/bin:$TRAVIS_BUILD_DIR/vendor/bin:$PATH"

  # Build the Lightning code base.
  - composer install

  # Install Lightning.
  - drush site:install headless_lightning --yes --db-url sqlite://db.sqlite
  - chmod -R +w docroot/sites/default

  # Update code base to HEAD.
  - composer nuke
  - composer require acquia/headless_lightning:dev-master --no-update
  - composer update

  # Run database and Lightning config updates.
  - drush cache-rebuild
  - drush updatedb --yes
  - drush update:lightning --no-interaction

before_script:
  - drush runserver --default-server=builtin 8080 &>/dev/null &
  - chromedriver --port=4444 &
  - cd docroot

script:
  - phpunit -c core --group headless --debug

matrix:
  fast_finish: true
